// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMP_API.Models.Contexts;

#nullable disable

namespace OMP_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241215144027_migration10")]
    partial class migration10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OMP_API.Models.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRatePerHourBrutto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("baseRatePerHourBrutto");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__Contract__3213E83F3C20CDCF");

                    b.HasIndex("CustomerId");

                    b.ToTable("ContractTypes");
                });

            modelBuilder.Entity("OMP_API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Country__3213E83FAFE6F665");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("OMP_API.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<decimal>("ExchangeRateToDollar")
                        .HasColumnType("decimal(10, 4)")
                        .HasColumnName("exchangeRateToDollar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id")
                        .HasName("PK__Currenci__3213E83FD1F38041");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("OMP_API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3213E83F35E24FBE");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OMP_API.Models.CustomerModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<int?>("CustomerId1")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("moduleId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId1");

                    b.HasIndex("ModuleId");

                    b.ToTable("CustomerModules");
                });

            modelBuilder.Entity("OMP_API.Models.DebitNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currencyId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PK__DebitNot__3213E83FA5ACCDF3");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("DebitNote");
                });

            modelBuilder.Entity("OMP_API.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("PK__Errors__3213E83F89403E77");

                    b.HasIndex("CustomerId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("OMP_API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Groups__3213E83F53CA99A1");

                    b.HasIndex("CustomerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("OMP_API.Models.GroupMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__GroupMes__3213E83FDCCEBE82");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMessages");
                });

            modelBuilder.Entity("OMP_API.Models.GroupsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("groupId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("isOwner");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__GroupsUs__3213E83FF1D1464B");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupsUsers");
                });

            modelBuilder.Entity("OMP_API.Models.ImageInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("filePath");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__ImageInp__3213E83F78F8C9D2");

                    b.ToTable("ImageInput");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currencyId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceNetto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("priceNetto");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("ValueBrutto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valueBrutto");

                    b.Property<decimal>("ValueNetto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valueNetto");

                    b.Property<int?>("VatTax")
                        .HasColumnType("int")
                        .HasColumnName("vatTax");

                    b.Property<decimal?>("VatTaxValue")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("vatTaxValue");

                    b.HasKey("Id")
                        .HasName("PK__InvoiceC__3213E83F310AB2C4");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VatTax");

                    b.ToTable("InvoiceCost");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currencyId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceNetto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("priceNetto");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("ValueBrutto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valueBrutto");

                    b.Property<decimal>("ValueNetto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valueNetto");

                    b.Property<int?>("VatTax")
                        .HasColumnType("int")
                        .HasColumnName("vatTax");

                    b.Property<decimal?>("VatTaxValue")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("vatTaxValue");

                    b.HasKey("Id")
                        .HasName("PK__InvoiceI__3213E83FDCD6D769");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VatTax");

                    b.ToTable("InvoiceIncome");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10, 4)")
                        .HasColumnName("rate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__InvoiceT__3213E83F287EAB76");

                    b.HasIndex("CustomerId");

                    b.ToTable("InvoiceTaxRates");
                });

            modelBuilder.Entity("OMP_API.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("OMP_API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit")
                        .HasColumnName("isSeen");

                    b.Property<string>("NotificationSource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notificationSource");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notificationText");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83F27B0DAA5");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OMP_API.Models.NotificationsSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("NotificationSource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notificationSource");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83F329ED79A");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationsSubscribers");
                });

            modelBuilder.Entity("OMP_API.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractType")
                        .HasColumnType("int")
                        .HasColumnName("contractType");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currencyId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("hours");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PayrollTaxRateIds")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payrollTaxRateIds");

                    b.Property<decimal>("RatePerHourBrutto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ratePerHourBrutto");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PK__Payroll__3213E83FCDBD170F");

                    b.HasIndex("ContractType");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Payroll");
                });

            modelBuilder.Entity("OMP_API.Models.PayrollTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10, 4)")
                        .HasColumnName("rate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__PayrollT__3213E83FDB6ED523");

                    b.HasIndex("CustomerId");

                    b.ToTable("PayrollTaxRates");
                });

            modelBuilder.Entity("OMP_API.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Position__3213E83F16476757");

                    b.HasIndex("CustomerId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("OMP_API.Models.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("UserRecipientId")
                        .HasColumnType("int")
                        .HasColumnName("userRecipientId");

                    b.Property<int>("UserSenderId")
                        .HasColumnType("int")
                        .HasColumnName("userSenderId");

                    b.HasKey("Id")
                        .HasName("PK__PrivateM__3213E83F3BE648B5");

                    b.HasIndex("UserRecipientId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("OMP_API.Models.ReccuringCostInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoiceId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("nextDueDate");

                    b.HasKey("Id")
                        .HasName("PK__Reccurin__3213E83FF40254C6");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ReccuringCostInvoice");
                });

            modelBuilder.Entity("OMP_API.Models.ReccuringIncomeInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoiceId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("nextDueDate");

                    b.HasKey("Id")
                        .HasName("PK__Reccurin__3213E83F89099AD5");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ReccuringIncomeInvoice");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__SpecialG__3213E83F54E2EB48");

                    b.HasIndex("CustomerId");

                    b.ToTable("SpecialGroups");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroupsTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<int>("SpecialGroupId")
                        .HasColumnType("int")
                        .HasColumnName("specialGroupId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__SpecialG__3213E83F6FF0DB49");

                    b.HasIndex("SpecialGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialGroupsTickets");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroupsUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("isOwner");

                    b.Property<int>("SpecialGroupId")
                        .HasColumnType("int")
                        .HasColumnName("specialGroupId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__SpecialG__3213E83F7696AC27");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SpecialGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialGroupsUsers");
                });

            modelBuilder.Entity("OMP_API.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime")
                        .HasColumnName("completionTime");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DeadlineTime")
                        .HasColumnType("datetime")
                        .HasColumnName("deadlineTime");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("IsMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("isMeeting");

                    b.Property<DateTime?>("LateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("lateTime");

                    b.Property<int>("TaskRecipient")
                        .HasColumnType("int");

                    b.Property<int>("TaskSender")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Tasks__3213E83F964422DE");

                    b.HasIndex("TaskRecipient");

                    b.HasIndex("TaskSender");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("OMP_API.Models.TextInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("PK__TextInpu__3213E83F13DC09AD");

                    b.ToTable("TextInput");
                });

            modelBuilder.Entity("OMP_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("countryId");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleteDate");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("editDate");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("identityUserId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("positionId");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F4499240F");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OMP_API.Models.ContractType", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("ContractTypes")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__ContractT__custo__0E240DFC");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.CustomerModule", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMP_API.Models.Customer", null)
                        .WithMany("CustomerModules")
                        .HasForeignKey("CustomerId1");

                    b.HasOne("OMP_API.Models.Module", "Module")
                        .WithMany("CustomerModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("OMP_API.Models.DebitNote", b =>
                {
                    b.HasOne("OMP_API.Models.Currency", "CurrencyNavigation")
                        .WithMany("DebitNotes")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__DebitNote__curre__2AC04CAA");

                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("DebitNotes")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__DebitNote__custo__2BB470E3");

                    b.Navigation("CurrencyNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.Error", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("Errors")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Errors__customer__31A25463");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.Group", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("Groups")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Groups__customer__4D4A6ED8");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.GroupMessage", b =>
                {
                    b.HasOne("OMP_API.Models.Group", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMess__group__68F2894D");

                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("GroupMessages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMess__userI__67FE6514");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.GroupsUser", b =>
                {
                    b.HasOne("OMP_API.Models.Group", "Group")
                        .WithMany("GroupsUsers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupsUse__group__6339AFF7");

                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("GroupsUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupsUse__userI__62458BBE");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceCost", b =>
                {
                    b.HasOne("OMP_API.Models.Currency", "Currency")
                        .WithMany("InvoiceCosts")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__InvoiceCo__curre__17AD7836");

                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("InvoiceCosts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceCo__custo__16B953FD");

                    b.HasOne("OMP_API.Models.InvoiceTaxRate", "VatTaxNavigation")
                        .WithMany("InvoiceCosts")
                        .HasForeignKey("VatTax")
                        .HasConstraintName("FK__InvoiceCo__vatTa__18A19C6F");

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("VatTaxNavigation");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceIncome", b =>
                {
                    b.HasOne("OMP_API.Models.Currency", "Currency")
                        .WithMany("InvoiceIncomes")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__InvoiceIn__curre__1E5A75C5");

                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("InvoiceIncomes")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceIn__custo__1D66518C");

                    b.HasOne("OMP_API.Models.InvoiceTaxRate", "VatTaxNavigation")
                        .WithMany("InvoiceIncomes")
                        .HasForeignKey("VatTax")
                        .HasConstraintName("FK__InvoiceIn__vatTa__1F4E99FE");

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("VatTaxNavigation");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceTaxRate", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("InvoiceTaxRates")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceTa__custo__049AA3C2");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.Notification", b =>
                {
                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__userI__58BC2184");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.NotificationsSubscriber", b =>
                {
                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("NotificationsSubscribers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__userI__5D80D6A1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.Payroll", b =>
                {
                    b.HasOne("OMP_API.Models.ContractType", "ContractTypeNavigation")
                        .WithMany("Payrolls")
                        .HasForeignKey("ContractType")
                        .IsRequired()
                        .HasConstraintName("FK__Payroll__contrac__25FB978D");

                    b.HasOne("OMP_API.Models.Currency", "Currency")
                        .WithMany("Payrolls")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK__Payroll__currenc__25077354");

                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("Payrolls")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Payroll__custome__24134F1B");

                    b.Navigation("ContractTypeNavigation");

                    b.Navigation("Currency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.PayrollTaxRate", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("PayrollTaxRates")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__PayrollTa__custo__095F58DF");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.Position", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("Positions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Positions__custo__3E082B48");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.PrivateMessage", b =>
                {
                    b.HasOne("OMP_API.Models.User", "UserRecipient")
                        .WithMany("PrivateMessageUserRecipients")
                        .HasForeignKey("UserRecipientId")
                        .IsRequired()
                        .HasConstraintName("FK__PrivateMe__userR__6EAB62A3");

                    b.HasOne("OMP_API.Models.User", "UserSender")
                        .WithMany("PrivateMessageUserSenders")
                        .HasForeignKey("UserSenderId")
                        .IsRequired()
                        .HasConstraintName("FK__PrivateMe__userS__6DB73E6A");

                    b.Navigation("UserRecipient");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("OMP_API.Models.ReccuringCostInvoice", b =>
                {
                    b.HasOne("OMP_API.Models.InvoiceCost", "Invoice")
                        .WithMany("ReccuringCostInvoices")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Reccuring__invoi__30792600");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("OMP_API.Models.ReccuringIncomeInvoice", b =>
                {
                    b.HasOne("OMP_API.Models.InvoiceIncome", "Invoice")
                        .WithMany("ReccuringIncomeInvoices")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Reccuring__invoi__353DDB1D");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroup", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("SpecialGroups")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__custo__737017C0");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroupsTicket", b =>
                {
                    b.HasOne("OMP_API.Models.SpecialGroup", "SpecialGroup")
                        .WithMany("SpecialGroupsTickets")
                        .HasForeignKey("SpecialGroupId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__speci__7FD5EEA5");

                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("SpecialGroupsTickets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__userI__7EE1CA6C");

                    b.Navigation("SpecialGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroupsUser", b =>
                {
                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("SpecialGroupsUsers")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__custo__7834CCDD");

                    b.HasOne("OMP_API.Models.SpecialGroup", "SpecialGroup")
                        .WithMany("SpecialGroupsUsers")
                        .HasForeignKey("SpecialGroupId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__speci__7928F116");

                    b.HasOne("OMP_API.Models.User", "User")
                        .WithMany("SpecialGroupsUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialGr__userI__7A1D154F");

                    b.Navigation("Customer");

                    b.Navigation("SpecialGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OMP_API.Models.Task", b =>
                {
                    b.HasOne("OMP_API.Models.User", "TaskRecipientNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskRecipient")
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__TaskRecip__520F23F5");

                    b.HasOne("OMP_API.Models.Group", "TaskSenderNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskSender")
                        .IsRequired()
                        .HasConstraintName("FK__Tasks__TaskSende__5303482E");

                    b.Navigation("TaskRecipientNavigation");

                    b.Navigation("TaskSenderNavigation");
                });

            modelBuilder.Entity("OMP_API.Models.User", b =>
                {
                    b.HasOne("OMP_API.Models.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK__Users__countryId__47919582");

                    b.HasOne("OMP_API.Models.Customer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__customerI__469D7149");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("OMP_API.Models.User", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Users__IdentityUser");

                    b.HasOne("OMP_API.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("FK__Users__positionI__4885B9BB");

                    b.Navigation("Country");

                    b.Navigation("Customer");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OMP_API.Models.ContractType", b =>
                {
                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("OMP_API.Models.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OMP_API.Models.Currency", b =>
                {
                    b.Navigation("DebitNotes");

                    b.Navigation("InvoiceCosts");

                    b.Navigation("InvoiceIncomes");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("OMP_API.Models.Customer", b =>
                {
                    b.Navigation("ContractTypes");

                    b.Navigation("CustomerModules");

                    b.Navigation("DebitNotes");

                    b.Navigation("Errors");

                    b.Navigation("Groups");

                    b.Navigation("InvoiceCosts");

                    b.Navigation("InvoiceIncomes");

                    b.Navigation("InvoiceTaxRates");

                    b.Navigation("PayrollTaxRates");

                    b.Navigation("Payrolls");

                    b.Navigation("Positions");

                    b.Navigation("SpecialGroups");

                    b.Navigation("SpecialGroupsUsers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OMP_API.Models.Group", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupsUsers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceCost", b =>
                {
                    b.Navigation("ReccuringCostInvoices");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceIncome", b =>
                {
                    b.Navigation("ReccuringIncomeInvoices");
                });

            modelBuilder.Entity("OMP_API.Models.InvoiceTaxRate", b =>
                {
                    b.Navigation("InvoiceCosts");

                    b.Navigation("InvoiceIncomes");
                });

            modelBuilder.Entity("OMP_API.Models.Module", b =>
                {
                    b.Navigation("CustomerModules");
                });

            modelBuilder.Entity("OMP_API.Models.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OMP_API.Models.SpecialGroup", b =>
                {
                    b.Navigation("SpecialGroupsTickets");

                    b.Navigation("SpecialGroupsUsers");
                });

            modelBuilder.Entity("OMP_API.Models.User", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupsUsers");

                    b.Navigation("Notifications");

                    b.Navigation("NotificationsSubscribers");

                    b.Navigation("PrivateMessageUserRecipients");

                    b.Navigation("PrivateMessageUserSenders");

                    b.Navigation("SpecialGroupsTickets");

                    b.Navigation("SpecialGroupsUsers");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
